### ISSUE TITLE
Is there a roadmap? 

### ISSUE THREAD

**Issue by patrick-motard** [FryJay/MenuHammer#12]
It's mentioned in the README:
> It is still very much a work in progress. I have a large list of features I still want to add and some features are only partially implemented. Use at your own risk.

Is there a roadmap that we can contribute to? Perhaps some of the ideas can be listed on the [repo's project board](https://github.com/FryJay/MenuHammer/projects?type=beta)?

**Comment by FryJay** [comment]
Hi Patrick, sorry for the delay responding.  I haven't really worked on this in quite a while now as I no longer use it as much as I was when I made it.  Basically I switched jobs and I can't run Hammerspoon on my new work laptop due to company restrictions and automating work tasks was the primary reason I created it.  I may go back to working on it at some point but can't make any promises.
